import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms'; import { AfterViewInit,Component,ElementRef,OnDestroy,ViewChild } from '@angular/core'; import { Router,RouterLink } from '@angular/router'; import { IonButton,IonContent,IonIcon,IonSpinner,IonToggle } from '@ionic/angular/standalone'; import { addIcons } from 'ionicons'; import { cameraOutline,albumsOutline,swapHorizontalOutline } from 'ionicons/icons'; import { Subscription } from 'rxjs';
import { visionConfig } from '../../core/config/vision.config'; import type { FrameMetrics,ScannerState } from '../../core/models/vision.models'; import { FrameAnalysisService } from '../../core/services/frame-analysis.service'; import { VisionApiService } from '../../core/services/vision-api.service'; import { VoiceCommandService } from '../../core/services/voice-command.service';
@Component({
    selector: 'app-scanner', imports: [CommonModule, FormsModule, IonContent, IonButton, IonIcon, IonSpinner, IonToggle, RouterLink], templateUrl: './scanner.page.html', styleUrls: ['./scanner.page.scss', './scanner-gesture.scss']
})
export class ScannerPage implements AfterViewInit,OnDestroy{
 @ViewChild('video',{static:true}) video!:ElementRef<HTMLVideoElement>; @ViewChild('analysisCanvas',{static:true}) canvas!:ElementRef<HTMLCanvasElement>;
 state:ScannerState='IDLE'; autoCapture=true; processingEnabled=false; facingMode:'environment'|'user'='user'; stability=0; message='Iniciando cámara...'; error=''; flash=false; metrics?:FrameMetrics; voiceAvailable=false; voiceListening=false; voiceMessage='';
 private stream?:MediaStream;private timer?:number;private previous?:ImageData;private stableSince?:number;private lastCapture=0;processing=false;private lastHash?:string;private request?:Subscription;private voiceCommands?:Subscription;private voiceErrors?:Subscription;
 constructor(private frames:FrameAnalysisService,private voice:VoiceCommandService,private api:VisionApiService,private router:Router){addIcons({cameraOutline,albumsOutline,swapHorizontalOutline})}
 async ngAfterViewInit(){this.setupVoiceCommands();await this.startCamera()}
 ngOnDestroy(){this.stopCamera();this.voice.stop();this.voiceCommands?.unsubscribe();this.voiceErrors?.unsubscribe();this.request?.unsubscribe()}
 async startCamera(){this.stopCamera();this.state='IDLE';try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('NO_CAMERA');this.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:this.facingMode},width:{ideal:1280},height:{ideal:720}},audio:false});this.video.nativeElement.srcObject=this.stream;await this.video.nativeElement.play();this.message=this.processingEnabled?'Colocá el objeto dentro del recuadro':'Decí “comenzar análisis”';this.schedule();this.startVoice()}catch(e){this.state='ERROR';this.error=e instanceof DOMException&&e.name==='NotAllowedError'?'Necesitamos permiso para usar la cámara.':e instanceof DOMException&&e.name==='NotReadableError'?'La cámara está ocupada por otra aplicación.':'No hay una cámara disponible.'}}
 stopCamera(){if(this.timer)window.clearTimeout(this.timer);this.stream?.getTracks().forEach(t=>t.stop());this.stream=undefined}
 schedule(){if(!this.stream)return;this.timer=window.setTimeout(()=>{this.analyzeFrame();this.schedule()},visionConfig.frameIntervalMs)}
 analyzeFrame(){if(this.state==='RESULT'||this.video.nativeElement.readyState<2)return;if(this.processing)return;if(!this.processingEnabled){this.state='IDLE';this.message=this.voiceListening?'Decí “comenzar análisis”':'Presioná “Comenzar análisis”';return}const c=this.canvas.nativeElement,ctx=c.getContext('2d',{willReadFrequently:true});if(!ctx)return;ctx.drawImage(this.video.nativeElement,0,0,c.width,c.height);const image=ctx.getImageData(0,0,c.width,c.height);this.metrics=this.frames.measure(image,this.previous);this.previous=image;
  if(!this.metrics.acceptableExposure){this.resetStability('Ajustá la iluminación');return} if(!this.metrics.hasContent){this.state='SEARCHING';this.resetStability('Colocá el objeto dentro del recuadro');return} this.state='OBJECT_DETECTED';
  if(!this.metrics.sharp){this.resetStability('La imagen está desenfocada');return} if(this.metrics.motionScore>=visionConfig.maximumMotionScore){this.resetStability('Mantenelo quieto');return}
  this.state='WAITING_FOR_STABILITY';this.stableSince??=performance.now();this.stability=Math.min(1,(performance.now()-this.stableSince)/visionConfig.requiredStableTimeMs);this.message=this.stability<1?'Mantenelo quieto':'Objeto estable';if(this.autoCapture&&this.stability>=1&&Date.now()-this.lastCapture>=visionConfig.captureCooldownMs)this.capture(false,image)}
 resetStability(message:string){this.stableSince=undefined;this.stability=0;this.message=message}
 toggleProcessing(){this.setProcessing(!this.processingEnabled)}
 startVoice(){this.voiceAvailable=this.voice.available;this.voiceListening=this.voice.start();if(!this.voiceAvailable)this.voiceMessage='Comandos de voz no disponibles en este navegador'}
 private setupVoiceCommands(){this.voiceCommands=this.voice.commands$.subscribe(command=>{this.voiceMessage=command==='start'?'Comando reconocido: comenzar':'Comando reconocido: pausar';this.setProcessing(command==='start')});this.voiceErrors=this.voice.errors$.subscribe(message=>{this.voiceListening=false;this.voiceMessage=message})}
 private setProcessing(enabled:boolean){if(this.processingEnabled===enabled)return;this.processingEnabled=enabled;this.previous=undefined;this.resetStability(enabled?'Colocá el objeto dentro del recuadro':'Procesamiento pausado');this.state=enabled?'SEARCHING':'IDLE'}
 async capture(force=true,analysisImage?:ImageData){if(this.processing||!this.stream)return;const now=Date.now();if(!force&&now-this.lastCapture<visionConfig.captureCooldownMs)return;let hashImage=analysisImage??this.previous;if(!hashImage){const c=this.canvas.nativeElement,ctx=c.getContext('2d');if(!ctx)return;ctx.drawImage(this.video.nativeElement,0,0,c.width,c.height);hashImage=ctx.getImageData(0,0,c.width,c.height)}const hash=this.frames.perceptualHash(hashImage);if(!force&&this.lastHash&&this.frames.hashDistance(hash,this.lastHash)<=visionConfig.duplicateHashDistance){this.resetStability('Objeto ya analizado; cambiá el objeto');return}this.processing=true;this.state='CAPTURING';this.message='Capturando...';this.flash=true;setTimeout(()=>this.flash=false,180);
  const output=document.createElement('canvas'),v=this.video.nativeElement;output.width=v.videoWidth;output.height=v.videoHeight;output.getContext('2d')!.drawImage(v,0,0);const blob=await new Promise<Blob|null>(resolve=>output.toBlob(resolve,'image/jpeg',visionConfig.jpegQuality));if(!blob){this.fail('No fue posible capturar la imagen.');return}this.state='ANALYZING';this.message='Identificando objeto...';this.request=this.api.analyze(blob).subscribe({next:r=>{this.lastHash=hash;this.lastCapture=Date.now();this.processing=false;void this.router.navigate(['/result',r.analysisId],{state:{result:r.result}})},error:e=>this.fail(this.errorMessage(e))})}
 async switchCamera(){this.facingMode=this.facingMode==='environment'?'user':'environment';this.previous=undefined;await this.startCamera()}
 retry(){void this.startCamera()} private fail(message:string){this.processing=false;this.state='ERROR';this.error=message;this.message='No fue posible identificarlo'}
 private errorMessage(e:{status?:number;error?:{error?:{message?:string}}}){if(e.status===0)return 'No hay conexión con el servidor.';if(e.status===413)return 'La imagen es demasiado grande.';if(e.status===504)return 'La identificación tardó demasiado.';return e.error?.error?.message??'El servicio de visión no está disponible.'}
}
